GET student@MelvinLeroux-server.eddi.cloud/api/v1/sports
Content-Type: application/json

Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTI2NjA4NTcsImV4cCI6MTcxMjc0NzI1Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.lY8IUy0G8Ov_i4jIyXEtuTSfdKxrvlJ1ttZ34B_v6H4Do5Oyl3liqVba7bLJlVPBnOIA8TIUgUTPACO4EsI-0h0FoeIV3vgXgy3T4z_lL7eXLlEzR-QHe5p0Bgbnyt3rz5-zedmFMDCJkBocpS3KqN6at8u2mZ0MMDicqqmtk53bfxxys_8pPabm_OKu1aMYFVg3tmEf2PEaF1bm-WRY1OCGW2M_yfthpRO80kg5hpkfZ1cdLQx3Pfvl5KqZAYryRsmX0eZIwuOYpJx_xx3LcgVC1w7vWsQXxDOn7m92dra7uBCuhtnnK8L1ULDbHljBG6qiL0uEykKey4LSL3UqHQ
